### ISSUE TITLE
lapy compatibility

### ISSUE THREAD

**Issue by joseabernal** [NSBLab/BrainEigenmodes#2]
Hi,

As I try to run your code, I discover that the most recent version of LaPy (please see https://deep-mi.org/LaPy/dev/changes/latest.html) is incompatible with the version that your code depends on. Could you please let me know what specific version of lapy and other libraries I should use? Thanks.

Best wishes,

Jose

**Comment by jchrispang** [comment]
Hi Jose,

Yeah, I've just been made aware that the latest version of Lapy (v1.0.1) deprecated the modules TriaIO and TetIO, which are needed to run our codes.

If you revert back to Lapy v1.0.0, things should work out.

I'll update the README to highlight this compatibility issue.

Thanks

Regards,
James

**Comment by mobraine** [comment]
Hi, I believe TetIO was deprecated since lapy v1.0.0, as per the release information. Reverting back to v0.6.0 solved the import issue for me, but not v1.0.0
<img width="957" alt="image" src="https://github.com/NSBLab/BrainEigenmodes/assets/49314700/1af97a51-61f4-41dc-a741-532b30f78259">
